### PR TITLE
.gemrc and .sqlrc do not need to be executable

### PR DESCRIPTION
**Pull request by nicholaides**

### CODE REVIEW

**Comment by kliph** [comment]
@nicholaides pulling this branch and running `rcup -v` per the instructions in the README does not change executable permissions of my previously installed `.gemrc` and `.psqlrc`

**Comment by nicholaides** [comment]
> pulling this branch and running `rcup -v` per the instructions in the README does not change executable permissions of my previously installed .gemrc and .psqlrc

@kliph any recommendations? Should we just merge this and leave people with executable `.gemrc`? Should we make a PR on `rcup` to somehow address this across the board?

**Comment by kliph** [comment]
@nicholaides looks like the `-f` flag could replace the existing files with the files from the `promptworks/dotfiles` repo:

```
-f
if the rc file already exists in your home directory but does not match the file in your dotfiles directory, remove the rc file then create the symlink
```
- https://thoughtbot.github.io/rcm/rcup.1.html

**Comment by nicholaides** [comment]
If we can't make it update for people automatically, I think we merge this and figure out a way to communicate to people to use `-f`... or just let people have some executable files. I'm not worried about it from a security standpoint.

**Comment by nicholaides** [comment]
OMG this is so old I didn't realize this was my PR.

**Pull request merged**
